- name: "Set timezone to {{ timezone }}"
  timezone:
    name: "{{ timezone }}"

- name: updating hostname to {{ system_hostname }} (1/2)
  hostname:
    name: "{{ system_hostname }}"
  register: hostname_change

- name: updating hostname to {{ system_hostname }} (2/2)
  copy:
    content: "{{ system_hostname }}{{'\n'}}"
    dest: /etc/hostname
    backup: true
  register: hostname_change
  
- name: update /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '^127\.0\.0\.1'
    line: "127.0.0.1{{'\t'}}{{ system_hostname }}"
    backup: true
    state: present
  notify:
    - reboot host

- name: "Ensure mount directory exists"
  file:
    path: "{{ item.mount_path }}"
    state: directory
    mode: 0755
    owner: "{{ item.user }}"
    group: "{{ item.group }}"
  with_items:
    - "{{ filesystems }}"

- name: Mount up disk by label
  ansible.posix.mount:
    path: "{{ item.mount_path }}"
    src: "LABEL={{ item.label }}"
    fstype: "{{ item.fstype }}"
    state: mounted
  with_items:
    - "{{ filesystems }}"
