- name: "Set timezone to {{ timezone }}"
  timezone:
    name: "{{ timezone }}"

- name: updating hostname to {{ system_hostname }} (1/2)
  hostname:
    name: "{{ system_hostname }}"
  register: hostname_change

- name: updating hostname to {{ system_hostname }} (2/2)
  copy:
    content: "{{ system_hostname }}{{'\n'}}"
    dest: /etc/hostname
    backup: true
  register: hostname_change
  
- name: update /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '^127\.0\.0\.1'
    line: "127.0.0.1{{'\t'}}{{ system_hostname }}"
    backup: true
    state: present
  notify:
    - reboot host

- name: "Ensure mount directories exists"
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
    owner: "{{ user_PUID | default('0') }}"
    group: "{{ user_PGID | default('0') }}"
  with_items:
    - "{{ ssd_mount_path }}"
    - "{{ hdd_mount_path }}"

- name: Mount up SSD by label
  ansible.posix.mount:
    path: "{{ hdd_mount_path }}"
    src: "LABEL={{ ssd_label }}"
    fstype: ext4
    state: mounted

- name: Mount up HDD by label
  ansible.posix.mount:
    path: "{{ hdd_mount_path }}"
    src: "LABEL={{ hdd_label }}"
    fstype: ext4
    state: mounted